version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Packaging the application...
      - zip -r my-app.zip build/

artifacts:
  files:
    - my-app.zip
